batch_size: 64
train_path: ./dataset/
data_path: ./dataset/
epsilon: 0.05
margin: 5.0
model_name: Adv_Denoise_Resnext101
defense: true

print_log: false
query_limit: 10000
init_iter: 3
init_batch: 100
memory_size: 3

max_iters: 1
block_size:
  224x224: 32
  299x299: 23

local_forget_threshold:
  23: 1
  32: 1
  13: 1
  16: 1
  8: 2
  4: 2
  2: 3
  1: 3
  
save_path: output
save_prefix: CorrAttack_Flip_Defense
